package com.receiptofi.repository;

import com.receiptofi.domain.BaseEntity;
import com.receiptofi.domain.GenerateUserIds;

import org.springframework.data.mongodb.core.mapping.Document;

/**
 * User: hitender
 * Date: 4/13/14 5:18 PM
 */
public interface GenerateUserIdManager extends RepositoryManager<GenerateUserIds> {
    static String TABLE = BaseEntity.getClassAnnotationValue(GenerateUserIds.class, Document.class, "collection");

    String getNextAutoGeneratedUserId();
}
