package com.receiptofi.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * User: hitender
 * Date: 4/13/14 5:11 PM
 */
@SuppressWarnings ({
        "PMD.BeanMembersShouldSerialize",
        "PMD.LocalVariableCouldBeFinal",
        "PMD.MethodArgumentCouldBeFinal",
        "PMD.LongVariable"
})
@Document (collection = "GENERATE_USER_IDS")
public class GenerateUserIds {
    public static final long STARTING_USER_ID = 10_000_000_001L;

    @Id
    private final String className;

    @Field ("RID")
    private long autoGeneratedReceiptUserId = STARTING_USER_ID;

    public GenerateUserIds(String className) {
        this.className = className;
    }

    public static GenerateUserIds newInstance() {
        return new GenerateUserIds(GenerateUserIds.class.getName());
    }

    public long getAutoGeneratedReceiptUserId() {
        return autoGeneratedReceiptUserId;
    }
}
