package com.receiptofi.service;

import com.receiptofi.repository.GenerateUserIdManager;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * User: hitender
 * Date: 8/14/16 1:45 AM
 */
@Service
public class GenerateUserIdService {
    private static final Logger LOG = LoggerFactory.getLogger(GenerateUserIdService.class);

    private GenerateUserIdManager generateUserIdManager;
    private SkippedRidsService skippedRidsService;

    @Autowired
    public GenerateUserIdService(GenerateUserIdManager generateUserIdManager, SkippedRidsService skippedRidsService) {
        this.generateUserIdManager = generateUserIdManager;
        this.skippedRidsService = skippedRidsService;
    }

    public String getNextAutoGeneratedUserId() {
        String nextRid;
        if (skippedRidsService.hasSkippedRidsFound()) {
            nextRid = skippedRidsService.getNextAutoGeneratedUserId();
        } else {
            nextRid = generateUserIdManager.getNextAutoGeneratedUserId();
        }
        LOG.info("RID={} for new user", nextRid);
        return nextRid;
    }
}
